language: python

python:
  - "3.5"

sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: DOQM1rHl5SNp24AdtHiE6bY57FX1+tqMa8lmR6f6k/ZxNMIL8Lvf9R3Th9OJCUpyxPFjIPHCGznJaDijtDOwmsYllEQAGupwl/sTmk2mzo1bSwR0Le8WbpkPNo3Qac8WMt/AqFqtoxFrm2z88lMwi+hrZHm9NQlSrITvTtR+xGrz8P4w8gMq0jSlpoDxdvH6kp0vPzRkBv/cQJ+BaFX/+6wJNvMlQRwhrVC1D443YNiKm8eoSJwZguMaCHFqRN2Q0xtBq1Yg/KEEtTeZD7a8/6oXjoKOQr0yhxTUs7puuxQIjEm8Ru451QiNFh0csTTYzfamdnmZuelF/Ul52sKa+DbDte1BHkYZyGPebGYV4GqGmikE4flsBepSjQqtf31TAi7FWuAXEILrfTGk5Cnz5UFFOJFIB92Spt3kctS8tgKsfGqNKWPHZZlS1gofzwO6qDilcyjza/xwD5T0UJoHSZubzJ8caxwihzO1tA3.5JdaS1SfdcWkrOyN+LcXcJfCBCqbfBENlljKxstaJli0tiWR/Dfz2+LVoBfPFr5PR6W53L5Jh4g8NfYRYgVut+2yeoKhavCpk22fckpQY6K9+WQgeOLGaCbD9S9ugUGDJwy3l4VZLyvr7FFLlbBTDT8EhLVFF79brTfdLdTg3SXlZikDb7EYXRnVmCwlQ1FnoW8=

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="odoo/odoo"


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
