# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: Travis
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: This repository hosts official Swiss localization provided by the
  OCA.
repo_name: Odoo Swiss localization
repo_slug: l10n-switzerland
repo_website: https://github.com/OCA/l10n-switzerland
travis_apt_packages: []
travis_apt_sources: []
