name: test Odoo addons

on:
  pull_request:
  push:
    branches:
      - "12.0"
      - "12.0-ocabot*"

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/sbidoul/oca-ci/py3.6-odoo12.0:latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options:
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    env:
      PIP_EXTRA_INDEX_URL: "https://wheelhouse.shopinvader.com/simple/"
    steps:
      - uses: actions/checkout@v1
      - run: oca_install_addons
      - run: oca_init_test_database
      - run: oca_run_tests
      - uses: codecov/codecov-action@v1
