# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.8.0
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description:
  This project aim to deal with modules related to manage document printing and sending
  in a generic way.
repo_name: Odoo Printing Services and Printer related addons
repo_slug: report-print-send
repo_website: https://github.com/OCA/report-print-send
travis_apt_packages: []
travis_apt_sources: []
