language: python

python:
  - "3.5"

sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - libcups2-dev
      - cups

env:
  - VERSION="12.0" LINT_CHECK="1"
  - VERSION="12.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
  - VERSION="12.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0" TESTS="1"


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - git clone https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports
  - pip install unidecode
  - pip install git+https://github.com/aeroo/aeroolib#egg=aeroolib
  - pip install pycups
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
