# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.6.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Odoo modules related to Human Resources attendances management.
repo_name: Human Resources Attendance
repo_slug: hr-attendance
repo_website: https://github.com/OCA/hr-attendance
travis_apt_packages: []
travis_apt_sources: []
