# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Odoo Partner and Contact related addons
repo_name: Odoo Partner and Contact related addons
repo_slug: partner-contact
repo_website: https://github.com/OCA/partner-contact
travis_apt_packages: []
travis_apt_sources: []
