sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "3.5"

env:
  - VERSION="12.0" LINT_CHECK="1"
  - VERSION="12.0" LINT_CHECK="0"


before_install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly ${VERSION}
  - pip install coveralls flake8

script:
    - travis_run_tests ${VERSION}

after_success:
  coveralls
