# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.6.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: true
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Odoo modules related to Manufacturing
repo_name: Odoo Manufacturing Modules
repo_slug: manufacture
repo_website: https://github.com/OCA/manufacture
travis_apt_packages: []
travis_apt_sources: []

