# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.6.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Advanced async job management for Odoo
repo_name: Odoo Queue Modules
repo_slug: queue
repo_website: https://github.com/OCA/queue
travis_apt_packages: []
travis_apt_sources: []
