# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.7.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Odoo modules for businesses that involves maintenance tasks.
repo_name: Maintenance
repo_slug: maintenance
repo_website: https://github.com/OCA/maintenance
travis_apt_packages: []
travis_apt_sources: []
